figure, 
subplot(1,2,1), stem(c,':','diamond','MarkerFaceColor','red'), ... 
    axis tight, title('Stem Chart') 
subplot(1,2,2), stem(c_norm,':','diamond','MarkerFaceColor','red'), ... 
    axis tight, title('Normalized Stem Chart')
